### ISSUE TITLE
archlinux使用出现错误

### ISSUE THREAD

**Issue by ghost** [taizilongxu/douban.fm#103]
Traceback (most recent call last):
  File "/usr/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.8', 'console_scripts', 'douban.fm')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/doubanfm/douban.py", line 15, in <module>
    from doubanfm import data
  File "/usr/lib/python2.7/site-packages/doubanfm/data.py", line 2, in <module>
    from doubanfm.config import db_config
  File "/usr/lib/python2.7/site-packages/doubanfm/config.py", line 199, in <module>
    db_config = Config()
  File "/usr/lib/python2.7/site-packages/doubanfm/config.py", line 72, in __init__
    self.login_data = self.get_login_data()
  File "/usr/lib/python2.7/site-packages/doubanfm/config.py", line 98, in get_login_data
    login_data = request_token()
  File "/usr/lib/python2.7/site-packages/doubanfm/API/login.py", line 56, in request_token
    email, password, captcha_solution, captcha_id = win_login()
  File "/usr/lib/python2.7/site-packages/doubanfm/API/login.py", line 23, in win_login
    get_capthca_pic(captcha_id)
  File "/usr/lib/python2.7/site-packages/doubanfm/API/login.py", line 101, in get_capthca_pic
    i = Image.open(StringIO(r.content))
  File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 2286, in open
    % (filename if filename else fp))
IOError: cannot identify image file <StringIO.StringIO instance at 0x7f66ea2d2368>

上次使用还好着重装系统再装就不好啦
用的yaourt里的包 pip install的douban.fm不可以用 Import SMplayer错误

**Comment by taizilongxu** [comment]
#97 可以试试github上的版本,试试看有没有问题, pip我这网络问题还没上传

**Comment by taizilongxu** [comment]
@fengyici 已经发布到pip 0.4.10版本, 升级试试看

**Comment by fengyici** [comment]
$ douban.fm
Traceback (most recent call last):
  File "/usr/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.10', 'console_scripts', 'douban.fm')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2704, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2377, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2383, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/doubanfm/douban.py", line 7, in <module>
    from player import MPlayer       # player
ImportError: cannot import name 'MPlayer'

卸载leyaourt的doubanfm 那个才0.4.8
pip安装的是410 错误提示如上
douban.fm是用的py2.7么？

**Comment by taizilongxu** [comment]
这是你默认环境是3.5导致的

**Comment by huiyiqun** [comment]
同样的问题

```
huiyiqun@edge ~/Source/douban.fm                                                                                                             [2:59:21] 
(venv)> $ ./venv/bin/douban.fm                                                                                                             [±master ●]
Traceback (most recent call last):
  File "./venv/bin/douban.fm", line 7, in <module>
    from doubanfm.douban import main
  File "/home/huiyiqun/Source/douban.fm/venv/lib/python3.5/site-packages/doubanfm/douban.py", line 7, in <module>
    from player import MPlayer       # player
ImportError: cannot import name 'MPlayer'
```

使用pip安装以及从github安装都有这个问题

**Comment by fengyici** [comment]
楼上那么github和pip都不行………………那怎么安？
yaourt？

**Comment by taizilongxu** [comment]
@fengyici  系统里有python2.7吗,  看你的运行pip是安装到python3下的包里了

**Comment by taizilongxu** [comment]
我记得是有pip2和pip3之分的, 你看看
```
»»»» ls -l /usr/local/bin/ | grep pip                                                                                                       
-rwxr-xr-x  1 root   admin       281 12 14 16:31 pip
-rwxr-xr-x  1 root   admin       283 12 14 16:31 pip2
-rwxr-xr-x  1 root   admin       287 12 14 16:31 pip2.7
lrwxr-xr-x  1 limbo  admin        32  9 18 15:48 pip3 -> ../Cellar/python3/3.4.3/bin/pip3
lrwxr-xr-x  1 limbo  admin        34  9 18 15:48 pip3.4 -> ../Cellar/python3/3.4.3/bin/pip3.4
```

**Comment by huiyiqun** [comment]
用pip2装就可以了 用aur当然也可以 我现在是用aur里那个包
