### ISSUE TITLE
怎么登录啊？

### ISSUE THREAD

**Issue by aixinlove** [taizilongxu/douban.fm#112]
输入用户名和密码后，提示输入（Solution），随便输入后说验证码错误

**Comment by taizilongxu** [comment]
什么系统?没有自动打开吗
验证码存放位置  /tmp/captcha_pic.jpg, 可以手动看一下然后输入

**Comment by aixinlove** [comment]
@taizilongxu 
debian jessie 系统，看到图片了，但是输入后就这样了
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.13', 'console_scripts', 'douban.fm')()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/douban.py", line 87, in main
    Router()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/douban.py", line 46, in __init__
    self.data = data.Data()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/data.py", line 23, in __init__
    self.playlist = Playlist()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/model.py", line 38, in __init__
    self._get_first_song()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/model.py", line 55, in _func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/model.py", line 77, in _get_first_song
    song = douban.get_first_song()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/api.py", line 144, in get_first_song
    return self.requests_url('n')
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/api.py", line 135, in requests_url
    raise APIError(err)
doubanfm.exceptions.APIError: list index out of range

**Comment by taizilongxu** [comment]
我的也是jessie系统, 试了下可以运行的,  看样子是不是网络有什么问题呢?
