### ISSUE TITLE
树莓派 第一次打开成功之后均失败

### ISSUE THREAD

**Issue by HuanDeng** [taizilongxu/douban.fm#116]
➔ Email: huan18616397225
➔ Password:
➔ Solution: trade
♥ Get local token - Username: huan18616397225
♥ Get channel [ OK ]
♥ Get volume [ OK ]
♥ Get theme [ OK ]
♥ Get keys  [ OK ]
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.13', 'console_scripts', 'douban.fm')()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/douban.py", line 87, in                                                                                                  main
    Router()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/douban.py", line 46, in                                                                                                  __init__
    self.data = data.Data()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/data.py", line 23, in __                                                                                                 init__
    self.playlist = Playlist()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/model.py", line 38, in _                                                                                                 _init__
    self._get_first_song()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/model.py", line 55, in _                                                                                                 func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/model.py", line 77, in _                                                                                                 get_first_song
    song = douban.get_first_song()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/api.py", line 144, i                                                                                                 n get_first_song
    return self.requests_url('n')
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/api.py", line 135, i                                                                                                 n requests_url
    raise APIError(err)
doubanfm.exceptions.APIError: No JSON object could be decoded

**Comment by HuanDeng** [comment]
原来我被识别成机器人了
