### ISSUE TITLE
已经解决 //验证用户后报错，请求帮助，谢谢

### ISSUE THREAD

**Issue by songsanren** [taizilongxu/douban.fm#118]
Get channel [ OK ]
♥ Get volume [ OK ]
♥ Get theme [ OK ]
♥ Get keys  [ OK ]
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/doubanfm/douban.py", line 87, in main
    Router()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/douban.py", line 46, in __init__
    self.data = data.Data()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/data.py", line 23, in __init__
    self.playlist = Playlist()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 38, in __init__
    self._get_first_song()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 55, in _func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 77, in _get_first_song
    song = douban.get_first_song()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 144, in get_first_song
    return self.requests_url('n')
  File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 135, in requests_url
    raise APIError(err)
doubanfm.exceptions.APIError: list index out of range

系统 osx 10.11

**Comment by songsanren** [comment]
在使用之间，建议用浏览器登陆豆瓣fm(听歌，点红心），我之后没有遇到这个问题。

**Comment by taizilongxu** [comment]
cookie 过期了是吗?

**Comment by songsanren** [comment]
可能是的，还有不知道是不是因为我豆瓣账号之前没使用过豆瓣fm的原因。

**Comment by Rex-Diego** [comment]
第一次输入邮箱密码和验证码之后显示
➔ Solution: effect
帐号不能为空
(╯‵□′)╯︵┻━┻: 帐号不能为空

不知道怎么解决，可能是获取token的网页发生了变化？命令行下输入的email地址无法返回给响应位置了？
