### ISSUE TITLE
卡在"切换频道中..."

### ISSUE THREAD

**Issue by xtk923** [taizilongxu/douban.fm#125]
切换频道之后跳出以下错误，随后界面卡在“切换频道中...”

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 66, in _watchdog
    song = douban.get_song(sid)
  File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 152, in get_song
    return self.requests_url('p', sid=sid)
  File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 135, in requests_url
    raise APIError(err)
APIError: list index out of range

**Comment by xtk923** [comment]
后来发现问题只是在切换到红心兆赫的情况，所以怀疑是token文件的问题。删除token之后，登录时不能获得验证码，提示"cannot concatenate 'str' and 'int' objects" 
重新安装douban.fm之后，登录时虽然提供了账号密码和验证码，还是提示“账号不能为空”。试过单独在virtualenv里面装，也是这个问题。

**Comment by taizilongxu** [comment]
期间可能是豆瓣的api变了导致失败了
