### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-jmcln825/pyobjc-framework-Accounts

### ISSUE THREAD

**Issue by iphone-andy** [taizilongxu/douban.fm#128]
安装的时候报错了、能告知是什么原因么

**Comment by ChenghaoQ** [comment]
抱歉我刚刚看到，它添加long description 以后的错误，上一个版本没有这个错误，我尽快修复，抱歉

2016年6月20日星期一，qiucanqing <notifications@github.com> 写道：

**Comment by ChenghaoQ** [comment]
抱歉，刚刚这条发错了

2016年6月22日星期三，Chenghao Qian <ch.jakobqian@gmail.com> 写道：

**Comment by SmarmyWu** [comment]
安装遇到了同样的问题。

**Comment by taizilongxu** [comment]
是 macOS 10.12吗?

**Comment by iphone-andy** [comment]
OK、我又回来了、我把以前的更新了、现在安装成功了、但是登录完以后就报错了

`♥ Get local token - Username: NEG
♥ Get channel [ OK ]
♥ Get volume [ OK ]
♥ Get theme [ OK ]
♥ Get keys  [ OK ]
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.15', 'console_scripts', 'douban.fm')()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/douban.py", line 101, in main
    router = Router()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/douban.py", line 47, in __init__
    self.data = data.Data()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/data.py", line 23, in __init__
    self.playlist = Playlist()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 40, in __init__
    self._get_first_song()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 57, in _func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 82, in _get_first_song
    song = douban.get_first_song()
  File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 172, in get_first_song
    return self.requests_url('n')
  File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 163, in requests_url
    raise APIError(err)
doubanfm.exceptions.APIError: list index out of range`
