### ISSUE TITLE
不能获取歌词...

### ISSUE THREAD

**Issue by kexul** [taizilongxu/douban.fm#140]
Exception in thread Thread-32:
                              Traceback (most recent call last):
                                                                  File "/home/kkk/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                                           self.run()
       File "/home/kkk/anaconda2/lib/python2.7/threading.py", line 754, in run
                                                                                  self.__target(*self.__args, **self.__kwargs)
                                                File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/controller/main_controller.py", line 195, in _watchdog_time
              self.view.display()
                                   File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/views/lrc_view.py", line 32, in display
                                                             self.set_dal()
                                                                             File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/views/lrc_view.py", line 22, in set_dal
                       dal = LrcDal(self.data, self.lrc_offset)
                                                                 File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/dal/dal_lrc.py", line 10, in __init__
         self.lrc = data.lrc
                              File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/data.py", line 50, in lrc
                                          return self.playlist.get_lrc()
                                                                          File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/model.py", line 92, in get_lrc
           self._lrc = douban.get_lrc(self._playingsong)
                                                          File "/home/kkk/anaconda2/lib/python2.7/site-packages/doubanfm/API/api.py", line 241, in get_lrc
                                                                              lrc_dic = lrc2dict(lyric['lyric'])
                                KeyError: 'lyric'

**Comment by kexul** [comment]
惊呆了，，，４天前ｆｉｘ的。。。为什么。。。

**Comment by blambin** [comment]
@kexul pypy上还没更新。。

**Comment by kexul** [comment]
@blambin 我试着把ｇｉｔｈｕｂ上的文件下载，直接覆盖我本地的文件，，，，还是不行。。。

**Comment by blambin** [comment]
@kexul 用我提交的那个文件改一下就好了
