### ISSUE TITLE
No module named 'Queue'

### ISSUE THREAD

**Issue by chy996633** [taizilongxu/douban.fm#154]
`back@samuel-all:~$ douban.fm 
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.15', 'console_scripts', 'douban.fm')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/doubanfm/douban.py", line 10, in <module>
    import Queue
ImportError: No module named 'Queue'`

ubuntu 16.04 LTS , python3

**Comment by zhuxi0511** [comment]
不兼容python3的关系，用python2安装吧
