### ISSUE TITLE
更新出错

### ISSUE THREAD

**Issue by mengyingbo** [taizilongxu/douban.fm#159]
----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-64d15sv0/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ybfo8r2e-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-64d15sv0/cffi/
pi@raspberrypi:~ $ douban.fm
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 7, in <module>
    from doubanfm.douban import main
  File "/usr/local/lib/python3.5/dist-packages/doubanfm/douban.py", line 10, in <module>
    import Queue
ImportError: No module named 'Queue'
pi@raspberrypi:~ $

**Comment by mengyingbo** [comment]
python3.5 
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

**Comment by terryoy** [comment]
看起来是python3下面应用了python2的库，python3下面包名是queue。。所以python3的移植到底做完了没有？我打算先过一遍看看功能怎么样。

**Comment by terryoy** [comment]
https://github.com/taizilongxu/douban.fm/issues/154 重复了
