### ISSUE TITLE
Mac 10.10.1 打开失败

### ISSUE THREAD

**Issue by ddling** [taizilongxu/douban.fm#30]
/bin/sh: amixer: command not found
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.2.13', 'console_scripts', 'douban.fm')()
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 356, in load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2476, in load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2190, in load
  File "/usr/local/lib/python2.7/site-packages/douban/douban.py", line 25, in <module>
    class Win(cli.Cli):
  File "/usr/local/lib/python2.7/site-packages/douban/douban.py", line 43, in Win
    sound_card = 'Master' if subprocess.check_output('amixer | grep Master', shell=True) else 'PCM'
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'amixer | grep Master' returned non-zero exit status 1

没找到原因，囧

**Comment by taizilongxu** [comment]
OK,更新一下,是声卡问题, OSX 没有 amixer 命令,没做异常处理

    sudo pip install --upgrade douban.fm

**Comment by ddling** [comment]
好了，谢谢啊！

**Comment by ddling** [comment]
好了，谢谢啊！
