### ISSUE TITLE
douban.fm无法运行成功

### ISSUE THREAD

**Issue by Blackrose** [taizilongxu/douban.fm#37]
Mac下通过pip安装douban.fm成功后，执行douban.fm报出错误，如下：

Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests

termcolor和requests已经安装，我的Mac版本是10.9.5

**Comment by taizilongxu** [comment]
试试这个 

    easy_install --upgrade requests

**Comment by Blackrose** [comment]
已解决，谢谢
