### ISSUE TITLE
运行后报错

### ISSUE THREAD

**Issue by urmyfaith** [taizilongxu/douban.fm#38]
osx 10.2

```
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.2.8', 'console_scripts', 'douban.fm')()
  File "build/bdist.macosx-10.10-intel/egg/douban/douban.py", line 187, in main
  File "build/bdist.macosx-10.10-intel/egg/douban/douban.py", line 43, in __init__
  File "build/bdist.macosx-10.10-intel/egg/douban/douban.py", line 94, in play
  File "build/bdist.macosx-10.10-intel/egg/douban/douban_token.py", line 154, in get_song
IndexError: pop from empty list

```

**Comment by taizilongxu** [comment]
每次都出现吗?

**Comment by urmyfaith** [comment]
直接下载安装包,或git clone,没有安装mplayer的时候一直报错.


看了下报错信息:

```
pop from empty list
```

我以为是我的收藏列表为空,就下载了app,收藏了几个.发现还是报错.


最后安装了mplyer之后,可以播放了.


我以为你的这个python setup.py install,可以直接运行了的.

osx貌似用afplay,mpg123都可以.
