### ISSUE TITLE
ArchLinux下的错误

### ISSUE THREAD

**Issue by Inkiron** [taizilongxu/douban.fm#47]
Traceback (most recent call last):
  File "/usr/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.2.15', 'console_scripts', 'douban.fm')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/douban/douban.py", line 502
    print self.win.TITLE
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by taizilongxu** [comment]
目前只兼容python2.7,暂时不兼容3+

**Comment by Hexcles** [comment]
文件头已经指定了使用 python2 运行，所以直接 chmod +x douban.py 之后运行是没有问题的。

我对 PyPi 不熟悉，打包的时候是不是有办法指定不论是用 pip3 还是 pip2 安装最后都用 Python 2 运行？
