### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6

### ISSUE THREAD

**Issue by Hexcles** [taizilongxu/douban.fm#60]
On startup:

```
Traceback (most recent call last):
  File "/home/robot/studio/douban.fm/douban/douban.py", line 775, in <module>
    main()
  File "/home/robot/studio/douban.fm/douban/douban.py", line 772, in main
    Win(douban)
  File "/home/robot/studio/douban.fm/douban/douban.py", line 120, in __init__
    self.display()
  File "/home/robot/studio/douban.fm/douban/douban.py", line 210, in display
    cli.Cli.display(self)
  File "/home/robot/studio/douban.fm/douban/cli.py", line 73, in display
    line = '%s %s %s' % (prefix, i, suffix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

**Comment by taizilongxu** [comment]
把eval()改成json有许多编码问题,真的是太蛋疼了
