### ISSUE TITLE
Centos 系统下启动报错，已安装Mplayer

### ISSUE THREAD

**Issue by mycheryhr** [taizilongxu/douban.fm#75]
♥ Get local token - user_name: Mr黄瑞
♥ Get local config [ ok ]
♥ Get channels  [ ok ]
♥ Check pro  [ ok ]
Traceback (most recent call last):
  File "/usr/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.3.0', 'console_scripts', 'douban.fm')()
  File "/usr/lib/python2.6/site-packages/douban/douban.py", line 740, in main
    Win(douban)
  File "/usr/lib/python2.6/site-packages/douban/douban.py", line 103, in __init__
    super(Win, self).__init__(self._lines)
  File "/usr/lib/python2.6/site-packages/douban/cli.py", line 44, in __init__
    self.screen_height, self.screen_width = self.linesnum()  # 屏幕显示行数
  File "/usr/lib/python2.6/site-packages/douban/cli.py", line 49, in linesnum
    num = subprocess.check_output('stty size', shell=True)
AttributeError: 'module' object has no attribute 'check_output'

**Comment by taizilongxu** [comment]
只支持2.7版本，这个报错看起来像是2.6版本的subprocess模块的问题。
