### ISSUE TITLE
error when running under virtualenv

### ISSUE THREAD

**Issue by huiyiqun** [taizilongxu/douban.fm#78]
The version in pypi is outdated, but I'd not like to `python setup.py install` with root, so I run it under virtual env(archlinux).

```
cd douban.fm
virtualenv2 venv
. ./venv/bin/activate
python setup install
./venv/bin/douban.fm
```

Then, it failed with following message:
```
Traceback (most recent call last):
  File "./venv/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.3.0', 'console_scripts', 'douban.fm')()
  File "/home/huiyiqun/Source/douban.fm/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/huiyiqun/Source/douban.fm/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/huiyiqun/Source/douban.fm/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/huiyiqun/Source/douban.fm/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/douban/douban.py", line 7, in <module>
  File "/home/huiyiqun/Source/douban.fm/build/lib/douban/cli.py", line 29, in <module>
    from colors import color_func
  File "/home/huiyiqun/Source/douban.fm/build/lib/douban/colors.py", line 89, in <module>
    c = config.get_default_theme(THEME[0])
  File "/home/huiyiqun/Source/douban.fm/build/lib/douban/config.py", line 115, in get_default_theme
    # path = '/Users/limbo/Cloud/cli/douban/colorset/default.json'
IOError: [Errno 20] Not a directory: '/home/huiyiqun/Source/douban.fm/venv/lib/python2.7/site-packages/douban.fm-0.3.0-py2.7.egg/douban/colorset/default.json'
```

It seems `os.path.dirname(__file__)` is pointed to `venv/lib/python2.7/site-packages/douban.fm-0.3.0-py2.7.egg/douban`.

Could it be fixed? or maybe I did not got the way?

**Comment by taizilongxu** [comment]
下载更新以下0.3.1版本看看是不是解决了?

**Comment by huiyiqun** [comment]
已经修复了
