### ISSUE TITLE
打开后错误无法播放，mint17系统

### ISSUE THREAD

**Issue by ShiftWang** [taizilongxu/douban.fm#79]
Exception in thread Thread-1:
                             Traceback (most recent call last):
                                                                 File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                           self.run()
                                                                       File "/usr/lib/python2.7/threading.py", line 763, in run
                                                   self.__target(*self.__args, **self.__kwargs)
                 File "/usr/local/lib/python2.7/dist-packages/douban/douban.py", line 251, in play
                      self.playingsong = self.get_song()
                                                          File "/usr/local/lib/python2.7/dist-packages/douban/douban.py", line 242, in get_song
                                                                   self.get_playlist()
        File "/usr/local/lib/python2.7/dist-packages/douban/douban.py", line 238, in get_playlist
                     self.playlist = self.douban.get_playlist(self._channel)
                                                                              File "/usr/local/lib/python2.7/dist-packages/douban/douban_token.py", line 276, in get_playlist
                 return eval(s)['song']
                                         File "<string>", line 1, in <module>
                                                                             NameError: name 'false' is not defined

**Comment by imlonghao** [comment]
同样的问题，希望能够解决！
Archlinux系统

**Comment by taizilongxu** [comment]
OK,确实是用不了了,明天晚上修复一下

**Comment by taizilongxu** [comment]
有可能是token过认证时间了, 可以删了.doubanfm_token试试看

**Comment by imlonghao** [comment]
应该不会是这个问题吧，我今天才装的douban.fm，然后就去登录，然后就出现这个问题了。
所以，应该不是过期把？

**Comment by taizilongxu** [comment]
在pip上新发了一版噶, 升级试试看解决了吗

**Comment by imlonghao** [comment]
我用AUR安装的...
现在AUR上面可以更新么？

**Comment by taizilongxu** [comment]
python的包用pip装最好啦, 可以试试
sudo pip install douban.fm 就好了

**Comment by imlonghao** [comment]
搞定，正常工作

**Comment by taizilongxu** [comment]
@ShiftWang 不知道解决了吗
