### ISSUE TITLE
raspberrypi没有notify-send，能改为可选项吗？

### ISSUE THREAD

**Issue by spin6lock** [taizilongxu/douban.fm#80]
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/notification.py", line 131, in send_notify
self.init_notification(playingsong)
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/notification.py", line 119, in init_notification
content.decode('utf-8'), self.cover_file.name)
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/notification.py", line 26, in send_notification
send_Linux_notify(title, content, cover_file)
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/notification.py", line 42, in send_Linux_notify
subprocess.call(command + [title, content])
File "/usr/lib/python2.7/subprocess.py", line 493, in call
return Popen(*popenargs, **kwargs).wait()
File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

目前系统里发送notify的包，似乎只有这两个
notification-daemon - daemon for displaying passive pop-up notifications
notify-osd - daemon that displays passive pop-up notifications

**Comment by taizilongxu** [comment]
恩,OK  这个下个版本加进来

**Comment by spin6lock** [comment]
这就一年了……

**Comment by taizilongxu** [comment]
已经取消了 :-)

**Comment by spin6lock** [comment]
谢谢🙏
