### ISSUE TITLE
subprocess找不到文件

### ISSUE THREAD

**Issue by spin6lock** [taizilongxu/douban.fm#81]
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/douban.py", line 258, in play
self.player.start(song['url'].replace('\\', ''))
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/player.py", line 159, in start
self._run_player(['-volume', str(self._volume), url])
File "/usr/local/lib/python2.7/dist-packages/douban.fm-0.3.1-py2.7.egg/douban/player.py", line 73, in _run_player
preexec_fn=os.setsid
File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

这个没看懂，是args构造的时候少了什么吗？之前用树莓派跑是没有问题的，系统也是同样的系统，可是换了树莓派2就跑不起来了，囧rz

**Comment by spin6lock** [comment]
新装的系统，忘了装mplayer了，抱歉

**Comment by taizilongxu** [comment]
OK  下次我加个异常
