### ISSUE TITLE
Unable to start douban.fm

### ISSUE THREAD

**Issue by huiyiqun** [taizilongxu/douban.fm#90]
显示如下：
```
Exception in thread Thread-1:
                             Traceback (most recent call last):
                                                                 File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
                                                                                                                                             self.run()

  File "/usr/lib64/python2.7/threading.py", line 763, in run
                                                                self.__target(*self.__args, **self.__kwargs)
                                                                                                              File "build/bdist.linux-x86_64/egg/douban/douban.py", line 256, in play
                                  self.set_suffix_selected(song)
                                                                  File "build/bdist.linux-x86_64/egg/douban/douban.py", line 122, in set_suffix_selected
     public_time = color_func(self.c['PLAYINGSONG']['publictime'])(song['public_time']) or ''
                                                                                             KeyError: 'public_time'

```

**Comment by taizilongxu** [comment]
这个是豆瓣fm的api更改了，更新一下新版本，已修复了这个问题: )

**Comment by huiyiqun** [comment]
从git里面的下载的代码 问题解决了 重新 build和install了一下
