### ISSUE TITLE
0.4.4 错误

### ISSUE THREAD

**Issue by wenLiangcan** [taizilongxu/douban.fm#95]
```
 doubanfm
♥ Get local token - Username: xxx
♥ Get channel [ OK ]
♥ Get volume [ OK ]
♥ Get theme [ OK ]
♥ Get keys  [ OK ]








Exception in thread Thread-5:
                             Traceback (most recent call last):
                                                                 File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                   self.run()
                                                               File "/usr/lib/python2.7/threading.py", line 763, in run
                                   self.__target(*self.__args, **self.__kwargs)
                                                                                 File "/usr/lib/python2.7/site-packages/doubanfm/controller/main_controller.py", line 154, in _watchdog_time
                self.view.display()
                                     File "/usr/lib/python2.7/site-packages/doubanfm/views/main_view.py", line 58, in display
                                         self.set_dal()
                                                         File "/usr/lib/python2.7/site-packages/doubanfm/views/main_view.py", line 27, in set_dal
                                                             dal = MainDal(self.data)
                                                                                       File "/usr/lib/python2.7/site-packages/doubanfm/dal/dal_main.py", line 40, in __init__
                                                                                         self.song_total_time = playingsong['length']
                                             TypeError: 'NoneType' object has no attribute '__getitem__'

                Exception in thread Thread-1:
                                             Traceback (most recent call last):
                                                                                 File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                                   self.run()
                                                                               File "/usr/lib/python2.7/threading.py", line 763, in run
                                                   self.__target(*self.__args, **self.__kwargs)
         File "/usr/lib/python2.7/site-packages/doubanfm/player.py", line 192, in _watchdog_queue
             self.start(self.queue.get_song()['url'])
                                                       File "/usr/lib/python2.7/site-packages/doubanfm/controller/main_controller.py", line 51, in _func
                                                                    tmp = func(self, *args, **kwargs)
               File "/usr/lib/python2.7/site-packages/doubanfm/controller/main_controller.py", line 70, in get_song
                               return self.data.get_song()
                                                            File "/usr/lib/python2.7/site-packages/doubanfm/douban.py", line 81, in get_song
                                                        playingsong = self.playlist.get_song(self.netease)
                    File "/usr/lib/python2.7/site-packages/doubanfm/model.py", line 49, in _func
            return func(*args, **kwargs)
                                          File "/usr/lib/python2.7/site-packages/doubanfm/model.py", line 111, in get_song
                                      url, kbps = Netease().get_url_and_bitrate(song['title'])
        File "/usr/lib/python2.7/site-packages/doubanfm/API/netease_api.py", line 63, in get_url_and_bitrate
                        song_id, bitrate = self.get_song_id(song_title)
                                                                         File "/usr/lib/python2.7/site-packages/doubanfm/API/netease_api.py", line 49, in get_song_id
                                                                                 song = self.search(song_title)
                         File "/usr/lib/python2.7/site-packages/doubanfm/API/netease_api.py", line 41, in search
                            return data['result']['songs'][0]
                                                             KeyError: 'songs'
```

一运行就这样了

**Comment by wenLiangcan** [comment]
刚运行了 3 此都是上面那样，现在发现又没问题了。。。。

**Comment by taizilongxu** [comment]
我这没有复现这个问题, 逻辑可能有些问题, 我再看看
