### ISSUE TITLE
ImportError: cannot import name IncompleteRead

### ISSUE THREAD

**Issue by dyis** [taizilongxu/douban.fm#96]
~$ douban.fm 
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.7', 'console_scripts', 'douban.fm')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/douban.py", line 15, in <module>
    from doubanfm import data
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/data.py", line 2, in <module>
    from doubanfm.config import db_config
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/config.py", line 11, in <module>
    from doubanfm.check_version import is_latest, update_package
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/check_version.py", line 4, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by dyis** [comment]
重装pip解决

sudo apt-get remove python-pip
sudo apt-get autoremove

wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py --no-check-certificate
sudo python get-pip.py
