### ISSUE TITLE
在树莓派上运行失败了？

### ISSUE THREAD

**Issue by harryprince** [taizilongxu/douban.fm#97]
命令行显示， 命令行版本的douban.fm停止了？

**Comment by taizilongxu** [comment]
有报错吗,  还有什么系统, douban.fm什么版本

**Comment by harryprince** [comment]
树莓派2，安装的是raspbian,然后douban.fm可以打开登陆，不过播放的时候后，提示这个服务现在下线了，播放不了。

**Comment by taizilongxu** [comment]
OK 豆瓣FM的API更改了, 暂时使用不了了, 这周末有时间我会更新一下

**Comment by harryprince** [comment]
万分感谢！

2015-11-04 22:54 GMT+08:00 hackerxu <notifications@github.com>:

**Comment by qida** [comment]
输入登录信息后，显示错误如下，希望对你有所帮助。也感谢你的付出。
➔ Password: 
Traceback (most recent call last):
  File "/usr/local/bin/douban.fm", line 9, in <module>
    load_entry_point('douban.fm==0.4.8', 'console_scripts', 'douban.fm')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/douban.py", line 15, in <module>
    from doubanfm import data
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/data.py", line 2, in <module>
    from doubanfm.config import db_config
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/config.py", line 199, in <module>
    db_config = Config()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/config.py", line 72, in __init__
    self.login_data = self.get_login_data()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/config.py", line 98, in get_login_data
    login_data = request_token()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/login.py", line 56, in request_token
    email, password, captcha_solution, captcha_id = win_login()
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/login.py", line 23, in win_login
    get_capthca_pic(captcha_id)
  File "/usr/local/lib/python2.7/dist-packages/doubanfm/API/login.py", line 101, in get_capthca_pic
    i = Image.open(StringIO(r.content))
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1980, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

**Comment by taizilongxu** [comment]
豆瓣增加了user-agent校验,  已经加上了, 下载源码 然后sudo python setup.py install 安装下看看
