### ISSUE TITLE
brew install mplayer error

### ISSUE THREAD

**Issue by huguangju** [taizilongxu/douban.fm#99]
larsmagne/mplayer#2

**Comment by taizilongxu** [comment]
特地试了下, 一切正常, 应当是网络的事吧

**Comment by huguangju** [comment]
还是不行，有可能被墙吧。

`sudo pip install douban.fm` 安到最后报错:

```shell
Downloading pyobjc-framework-AddressBook-3.0.4.tar.gz (51kB)
    100% |████████████████████████████████| 53kB 5.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-yRbLrQ/pyobjc-framework-AddressBook/setup.py", line 35, in <module>
        if fn.startswith('_AddressBook')
      File "pyobjc_setup.py", line 460, in setup
        **k
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (pyobjc-core 2.5.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC), Requirement.parse('pyobjc-core>=3.0.4'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-yRbLrQ/pyobjc-framework-AddressBook
```

我是版本是 `2.7.10`, 是不是太低了？

**Comment by huguangju** [comment]
这样安装可以安上： `brew install --HEAD mplayer`
